version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports: 
      - "1434:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    container_name: teslodb
    volumes:
      - ./sqlvolume:/var/opt/mssql/data